version: 0.0
os: linux
files:
  - source: build/
    destination: /home/ubuntu/react-app
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      runas: ubuntu
