version: 0.0
os: linux
files:
  - source: /build
    destination: /var/www/react-app

hooks:
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 180
      runas: ubuntu
