trigger:
  - main

pool:
  name: 'SelfHostedLocal'

variables:
  buildDir: 'build'
  artifactName: 'react-app-build'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install Dependencies and Build React App'

  - script: |
      echo "Checking if build directory exists..."
      if exist "$(System.DefaultWorkingDirectory)\$(buildDir)" (
        echo "Build directory found!"
        dir "$(System.DefaultWorkingDirectory)\$(buildDir)"
      ) else (
        echo "Build directory NOT found!"
        exit /b 1
      )
    displayName: 'Verify Build Directory'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/$(buildDir)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Build Output to Artifact Staging Directory'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(artifactName)'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
