trigger:
  - main

pool:
  name: 'self-hosted'

variables:
  buildDir: 'build'
  artifactName: 'react-app-build'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install Dependencies and Build'

  

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(artifactName)'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/$(buildDir)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Build Output to Staging Directory'
