trigger:
  - main

pool:
  name: 'self-hosted'

variables:
  buildDir: 'Ariyakrishna/build'
  artifactName: 'react-app-build'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      cd Ariyakrishna
      npm install
      npm run build
    displayName: 'Install Dependencies and Build React App'

  - script: |
      echo "Checking build output..."
      ls -al $(System.DefaultWorkingDirectory)/$(buildDir)
    displayName: 'List Build Folder Contents'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/$(buildDir)'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Build Output to Artifact Staging Directory'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: '$(artifactName)'
      publishLocation: 'Container'
    displayName: 'Publish Build Artifacts'
