version: '3.8'
services:
  frontend:
    build: ./react-frontend
    image: three-tier-react-image
    container_name: three-tier-frontend-con
    ports:
      - "80:80"
    depends_on:
      - backend
    
   

  backend:
    build: ./backend
    image: three-tier-backend-image
    container_name: three-tier-backend-con
    ports:
      - "5000:5000"
    depends_on:
      - mongo
   

  mongo:
    image: mongo:latest
    container_name: three-tier-mongo-con
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db




volumes:
  mongo_data:
